// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/durableScanWorkerControl.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "a3a081cf3d6c6649ad442ebec6533c2669bfd3e11a6159568593c7cb0e9b8df2";
