import assert from "node:assert/strict";
import test from "node:test";

import { buildPersistedAuthoritySnapshot } from "../../base44/functions/persistDurableScanAuthorityV4/authoritySnapshot.js";
import { authoritySnapshotFromRows } from "../../base44/functions/getCustomerScanResultV4/projection.js";

const USER_ID = "6a72088398ef113a449fc6c8";
const SEALED_AT = "2026-09-14T22:49:23.940Z";
const REPAIR_CONTRACT = "repair_contract_v2_shadow_calibrated";
const REPAIR_PRIORITY = "repair_priority_v2_technical_severity";

// Sanitized from the failed unpaid production canary. Proofs, secrets and
// admission bearer material are intentionally excluded. The fixture keeps the
// live Base44 null/default shapes that can affect reconstruction.
function liveRows() {
  const run = {
    id: "6aa879ef240c2f14f7534c3a",
    project_id: "6aa7c638282426432180b7c2",
    owner_user_id: USER_ID,
    normalized_domain: "centerstreetlending.com",
    website_url: "https://centerstreetlending.com/",
    status: "complete",
    release_gate_eligible: true,
    score_is_provisional: false,
    evidence_quality_blocking: false,
    scope_type: "",
    parent_scan_id: "",
    requested_origin: "https://centerstreetlending.com",
    requested_path_prefix: "",
    path_prefix: "",
    discovered_from: "",
    user_confirmed: false,
    scanner_version: "python_scanner_v3_bounded_request",
    scanner_build_revision: "authenticated_health_probe_v1",
    scanner_wrapper_version: "python_scanner_v3_bounded_request",
    advanced_scan_backend: "python_scanner_api",
    deno_fallback_used: false,
    archetype_classifier_version: "archetype_classifier_v12_locale_normalized_structural_routes",
    review_version: "python_review_v2_structural_marketplace",
    review_evidence_calibration_version: "review_evidence_calibration_v6_health_score_v2",
    ai_review_backend: "python_review_api",
    python_review_fallback_used: false,
    beta_revision_fingerprint: "a511d61013ef9fe3",
    metadata_evidence_version: "metadata_evidence_v1_description_states",
    title_evidence_version: "title_evidence_v1_contextual_duplicates",
    pages_found: 184,
    pages_crawled: 150,
    pages_retained: 150,
    scan_status: "complete",
    review_confidence_state: "complete",
    evidence_quality_state: "representative",
    evidence_quality_score: 100,
    evidence_quality_reasons: ["representative_html_evidence"],
    usable_html_page_count: 150,
    representative_html_page_count: 150,
    default_route_page_count: 0,
    discovery_quality_state: "representative",
    evidence_quality_gate_version: "evidence_quality_gate_v2_shared_coverage_decision",
    scan_coverage: {
      urls_attempted: 152,
      usable_html_pages: 152,
      verified_http_failures: 0,
      access_unverified_pages: 0,
      non_html_resources: 0,
      unique_retained_destinations: 150,
    },
    coverage_authority_evidence: {
      coverage_authority_evidence_version: "coverage_authority_evidence_v2_authoritative",
      assessment: "sufficient",
      would_gate_as_insufficient: false,
      reasons: ["coverage_within_expected_sampling_bounds"],
      inventory: {
        discovered_target: 184,
        attempted: 150,
        retained_usable_html: 150,
        retained_representative_html: 150,
        default_route_pages: 0,
        final_url_duplicates_deduped: 2,
        queued_remaining: 12,
        coverage_ratio: 0.815217,
      },
      terminal_reason: "page_cap_reached",
      inventory_proof: {
        sitemap_fetch_count: 1,
        sitemap_urls_discovered: 184,
        sitemap_failed: false,
        sitemap_failure_reason_buckets: {},
        sitemap_budget_exhausted: false,
        sitemap_fetch_limit_reached: false,
        queue_exhausted: false,
        failed_fetch_count: 0,
        positively_established: false,
      },
      thresholds: { min_retained_pages: 50, min_retained_ratio: 0.1, min_inventory_for_ratio_test: 100 },
    },
    classification_integrity: {
      version: "standard150_acceptance_evidence_v2_aggregate_rss_fail_closed",
      state: "classified",
      verdict: "classified",
      classifier_version: "archetype_classifier_v12_locale_normalized_structural_routes",
      evidence_sufficiency: "sufficient",
      usable_pages: 150,
      complete_small_site_inventory: false,
    },
    classification_verdict: "classified",
    peak_memory_bytes: 193871872,
    worker_peak_memory_bytes: 193871872,
    health_score: 60,
    health_grade: "Needs work",
    health_score_explanation: {
      version: "health_score_explanation_v1",
      starting_score: 100,
      final_score: 60,
      total_deduction: 40,
      deductions: [
        { category: "Search visibility", points: 15 },
        { category: "Search appearance", points: 9 },
        { category: "Page content", points: 8 },
        { category: "Website setup", points: 8 },
      ],
      coverage_ceiling: 100,
      applied_ceiling: 100,
      ceiling_reason: "",
      floor_applied: false,
      verification_findings_excluded: true,
    },
    customer_summary: "FixList recognized this as finance / insurance / lead generation and used the finance / insurance / lead generation playbook. The scanner reviewed 150 pages out of about 184 discovered URLs. Start with the highest-impact items on loan program pages, application pages, quote/contact forms.",
    next_best_step: "Fix broken location-page template content",
    no_high_confidence_findings: false,
    completed_at: SEALED_AT,
    authority_seal_version: "standard_review_snapshot_hmac_v6_report_evidence",
    authority_sealed_at: SEALED_AT,
    crawl_timing: {},
    sampling_evidence: {},
  };

  const fixList = {
    id: "6aa87a0513530c445fe4e62f",
    scan_run_id: run.id,
    project_id: run.project_id,
    website_url: run.website_url,
    ai_review_backend: "python_review_api",
    python_review_fallback_used: false,
    is_authoritative: true,
    health_score: 60,
    health_grade: "Needs work",
    scan_status: "complete",
    score_is_provisional: false,
    no_high_confidence_findings: false,
    total_fixes: 19,
    critical_count: 1,
    high_count: 13,
    medium_count: 3,
    low_count: 2,
    completed_count: 0,
    top_action_fix_ids: ["finding_f1edb27b70", "finding_30c1b97333", "finding_9078481e05"],
    repair_contract_version: REPAIR_CONTRACT,
    repair_snapshot_contract_version: REPAIR_CONTRACT,
    repair_snapshot_contract_complete: true,
    repair_priority_model_version: REPAIR_PRIORITY,
    canonical_action_fix_ids: ["finding_f1edb27b70", "finding_3c9a27f684e6"],
    generated_at: SEALED_AT,
  };

  const fixItems = [
    {
      id: "6aa87a05b5e44140628f81ad",
      fix_list_id: fixList.id,
      scan_run_id: run.id,
      project_id: run.project_id,
      fix_id: "finding_f1edb27b70",
      rule: "broken_location_template_content",
      category: "web_dev",
      customer_category: "Website setup",
      issue_title: "Fix broken location-page template content",
      plain_english_explanation: "FixList found unresolved location variables on a shared location template.",
      why_it_matters: "Publishing unresolved placeholders weakens trust and local relevance.",
      current_value: "#location#",
      recommended_value: "Fix the shared location template and verify representative pages.",
      simple_next_step: "",
      page_scope: "family",
      page_template_family: "location_landing",
      page_url: "/locations/alabama",
      affected_pages: ["/locations/alabama", "/locations/arkansas"],
      source_pages: ["/locations/alabama", "/locations/arkansas"],
      evidence_status: "",
      verification_state: "",
      limitation_code: null,
      confidence_score: 96,
      priority: "critical",
      difficulty: "developer",
      who_can_do_this: "your_web_person",
      requires_developer: true,
      requires_approval: false,
      can_auto_fix: false,
      estimated_time: "about 30–60 minutes",
      user_status: "open",
      completed_at: null,
      completed_by_user_id: null,
      first_seen_scan_run_id: null,
      carried_over: false,
      page_count: 0,
      family_breakdown: {},
      representative_pages_by_family: {},
      what_to_do_steps: ["Open the shared location-page template."],
      metadata_state_counts: { missing: 0, malformed: 0, empty: 0 },
      combined_rules: [],
      grouping_explanation: null,
      repair_contract_version: REPAIR_CONTRACT,
      repair_snapshot_contract_version: REPAIR_CONTRACT,
      repair_snapshot_contract_complete: true,
      repair_priority_model_version: REPAIR_PRIORITY,
      base_severity: "high",
      technical_severity_source: "defect_class",
      evidence_class: "confirmed_problem",
      action_priority: "fix_first",
      action_priority_score: 4374,
      priority_reason: "60 of 60 location pages checked are affected.",
      canonical_action_rank: 1,
      repair_identity_version: "repair_identity_v2_technical",
      repair_fingerprint: "8452f066cd3862809244629c",
      repair_identity_state: "provisional",
      repair_identity_stable: false,
      repair_surface: "",
      remediation_family: "",
      shared_repair_confirmed: false,
      priority_context: {
        version: REPAIR_PRIORITY,
        legacy_priority: "critical",
        base_severity: "high",
        technical_severity_source: "defect_class",
        evidence_class: "confirmed_problem",
        action_priority: "fix_first",
        action_priority_score: 4374,
        search_facing: false,
        affected_checked: 60,
        checked_eligible: 60,
        checked_coverage: 1,
        indexable_affected: 60,
        non_indexable_affected: 0,
        unknown_indexability_affected: 0,
        indexable_checked_eligible: 60,
        searchable_coverage: 1,
        important_affected: 60,
        shared_repair_confirmed: false,
        coverage_scope: "checked_sample",
      },
      repair_verification_state: null,
      rule_definition_version: null,
      comparison_profile_version: null,
      raw_finding: {
        verified_urls: [],
        repair_evidence_groups: [{
          fix_id: "finding_f1edb27b70",
          family: "location_landing",
          locale: "",
          representative_url: "/locations/alabama",
          affected_urls: ["/locations/alabama", "/locations/arkansas"],
          count: 2,
          priority: "critical",
          action_priority: "fix_first",
          evidence_class: "confirmed_problem",
          evidence_status: "",
          verification_state: "",
          repair_verification_state: "",
        }],
      },
    },
    {
      id: "6aa87a071c997ce194ef4268",
      fix_list_id: fixList.id,
      scan_run_id: run.id,
      project_id: run.project_id,
      fix_id: "finding_3c9a27f684e6",
      rule: "potential_orphan_pages",
      category: "indexability",
      customer_category: "Indexability",
      issue_title: "Verify sitemap-only pages are internally linked",
      plain_english_explanation: "The representative crawl found sitemap URLs without sampled internal links.",
      why_it_matters: "This is a verification lead rather than proof of orphaning.",
      current_value: "68 indexable sitemap URLs were not linked in the sampled crawl",
      recommended_value: "Confirm with a complete internal-link crawl or Search Console.",
      simple_next_step: "",
      page_scope: "mixed",
      page_template_family: "mixed",
      page_url: "/loan-overview",
      affected_pages: ["/loan-overview"],
      source_pages: ["/loan-overview"],
      evidence_status: "needs_verification",
      verification_state: "needs_verification",
      limitation_code: null,
      confidence_score: 64,
      priority: "low",
      difficulty: "moderate",
      who_can_do_this: "you_or_your_web_person",
      requires_developer: false,
      requires_approval: true,
      can_auto_fix: false,
      estimated_time: "about 2–4 hours",
      user_status: "open",
      completed_at: null,
      completed_by_user_id: null,
      first_seen_scan_run_id: null,
      carried_over: false,
      page_count: 0,
      family_breakdown: {},
      representative_pages_by_family: {},
      what_to_do_steps: ["Confirm the URLs with a complete internal-link crawl."],
      metadata_state_counts: { missing: 0, malformed: 0, empty: 0 },
      combined_rules: [],
      grouping_explanation: null,
      repair_contract_version: REPAIR_CONTRACT,
      repair_snapshot_contract_version: REPAIR_CONTRACT,
      repair_snapshot_contract_complete: true,
      repair_priority_model_version: REPAIR_PRIORITY,
      base_severity: "low",
      technical_severity_source: "rule_taxonomy",
      evidence_class: "opportunity",
      action_priority: "review",
      action_priority_score: 1138,
      priority_reason: "Affected evidence includes 5 customer-journey pages.",
      canonical_action_rank: 19,
      repair_identity_version: "repair_identity_v2_technical",
      repair_fingerprint: "89d008db70708423fb4b6dc2",
      repair_identity_state: "provisional",
      repair_identity_stable: false,
      repair_surface: "",
      remediation_family: "",
      shared_repair_confirmed: false,
      priority_context: {
        version: REPAIR_PRIORITY,
        legacy_priority: "low",
        base_severity: "low",
        technical_severity_source: "rule_taxonomy",
        evidence_class: "opportunity",
        action_priority: "review",
        action_priority_score: 1138,
        search_facing: true,
        affected_checked: 68,
        checked_eligible: null,
        checked_coverage: null,
        indexable_affected: 0,
        non_indexable_affected: 0,
        unknown_indexability_affected: 0,
        indexable_checked_eligible: null,
        searchable_coverage: null,
        important_affected: 5,
        shared_repair_confirmed: false,
        coverage_scope: "checked_sample",
      },
      repair_verification_state: null,
      rule_definition_version: null,
      comparison_profile_version: null,
      raw_finding: {
        verified_urls: [],
        repair_evidence_groups: [{
          fix_id: "finding_3c9a27f684e6",
          family: "mixed",
          locale: "",
          representative_url: "/loan-overview",
          affected_urls: ["/loan-overview"],
          count: 1,
          priority: "low",
          action_priority: "review",
          evidence_class: "opportunity",
          evidence_status: "needs_verification",
          verification_state: "needs_verification",
          repair_verification_state: "",
        }],
        non_scoring: true,
        score_impact: 0,
      },
    },
  ];

  return { run, fixList, fixItems };
}

test("Sep 15 live Base44 row shape rebuilds identically in V4 writer and reader", () => {
  const { run, fixList, fixItems } = liveRows();
  const writerSnapshot = buildPersistedAuthoritySnapshot({
    run,
    fixList,
    fixItems,
    userId: USER_ID,
    sealedAt: SEALED_AT,
  });
  const readerSnapshot = authoritySnapshotFromRows({ run, fixList, fixItems, userId: USER_ID });
  assert.deepEqual(readerSnapshot, writerSnapshot);
});
