import assert from "node:assert/strict";
import test from "node:test";

import { buildPersistedAuthoritySnapshot } from "../../base44/functions/persistDurableScanAuthorityV4/authoritySnapshot.js";
import { authoritySnapshotFromRows } from "../../base44/functions/getCustomerScanResultV4/projection.js";

const USER_ID = "6a72088398ef113a449fc6c8";
const SEALED_AT = "2026-09-14T22:49:23.940Z";
const REPAIR_CONTRACT = "repair_contract_v2_shadow_calibrated";
const REPAIR_PRIORITY = "repair_priority_v2_technical_severity";
const IDS = [
  "finding_f1edb27b70","finding_30c1b97333","finding_9078481e05","finding_0bb506f256",
  "finding_a037edf204","finding_50dd4eed83","finding_53ea35ee40","finding_0d4e7da6a7",
  "finding_118bbc1c07","finding_b798a04179","finding_6617bc2c6f","finding_8f6559de63",
  "finding_06ba427687","finding_b26c188a4d","finding_d182c4dc9a00","finding_07fb5115b7",
  "finding_214e1d8e46","finding_10630c4f31","finding_3c9a27f684e6",
];
const PRIORITIES = ["critical","high","high","medium","medium","high","high","medium","high","high","high","high","high","high","low","high","high","high","low"];
const ACTIONS = ["fix_first","important",...Array(16).fill("improve"),"review"];

function liveRun() {
  return {
    id: "6aa879ef240c2f14f7534c3a",
    project_id: "6aa7c638282426432180b7c2",
    owner_user_id: USER_ID,
    normalized_domain: "centerstreetlending.com",
    website_url: "https://centerstreetlending.com/",
    status: "complete",
    release_gate_eligible: true,
    score_is_provisional: false,
    evidence_quality_blocking: false,
    scope_type: "",
    parent_scan_id: "",
    requested_origin: "https://centerstreetlending.com",
    requested_path_prefix: "",
    path_prefix: "",
    discovered_from: "",
    user_confirmed: false,
    scanner_version: "python_scanner_v3_bounded_request",
    scanner_build_revision: "authenticated_health_probe_v1",
    scanner_wrapper_version: "python_scanner_v3_bounded_request",
    advanced_scan_backend: "python_scanner_api",
    deno_fallback_used: false,
    archetype_classifier_version: "archetype_classifier_v12_locale_normalized_structural_routes",
    review_version: "python_review_v2_structural_marketplace",
    review_evidence_calibration_version: "review_evidence_calibration_v6_health_score_v2",
    ai_review_backend: "python_review_api",
    python_review_fallback_used: false,
    beta_revision_fingerprint: "a511d61013ef9fe3",
    metadata_evidence_version: "metadata_evidence_v1_description_states",
    title_evidence_version: "title_evidence_v1_contextual_duplicates",
    pages_found: 184,
    pages_crawled: 150,
    pages_retained: 150,
    scan_status: "complete",
    review_confidence_state: "complete",
    evidence_quality_state: "representative",
    evidence_quality_score: 100,
    evidence_quality_reasons: ["representative_html_evidence"],
    usable_html_page_count: 150,
    representative_html_page_count: 150,
    default_route_page_count: 0,
    discovery_quality_state: "representative",
    evidence_quality_gate_version: "evidence_quality_gate_v2_shared_coverage_decision",
    scan_coverage: {
      urls_attempted: 152,
      usable_html_pages: 152,
      verified_http_failures: 0,
      access_unverified_pages: 0,
      non_html_resources: 0,
      unique_retained_destinations: 150,
    },
    coverage_authority_evidence: {
      coverage_authority_evidence_version: "coverage_authority_evidence_v2_authoritative",
      assessment: "sufficient",
      would_gate_as_insufficient: false,
      reasons: ["coverage_within_expected_sampling_bounds"],
      inventory: {
        discovered_target: 184,
        attempted: 150,
        retained_usable_html: 150,
        retained_representative_html: 150,
        default_route_pages: 0,
        final_url_duplicates_deduped: 2,
        queued_remaining: 12,
        coverage_ratio: 0.815217,
      },
      terminal_reason: "page_cap_reached",
      inventory_proof: {
        sitemap_fetch_count: 1,
        sitemap_urls_discovered: 184,
        sitemap_failed: false,
        sitemap_failure_reason_buckets: {},
        sitemap_budget_exhausted: false,
        sitemap_fetch_limit_reached: false,
        queue_exhausted: false,
        failed_fetch_count: 0,
        positively_established: false,
      },
      thresholds: { min_retained_pages: 50, min_retained_ratio: 0.1, min_inventory_for_ratio_test: 100 },
    },
    classification_integrity: {
      version: "standard150_acceptance_evidence_v2_aggregate_rss_fail_closed",
      state: "classified",
      verdict: "classified",
      classifier_version: "archetype_classifier_v12_locale_normalized_structural_routes",
      evidence_sufficiency: "sufficient",
      usable_pages: 150,
      complete_small_site_inventory: false,
    },
    classification_verdict: "classified",
    peak_memory_bytes: 193871872,
    worker_peak_memory_bytes: 193871872,
    health_score: 60,
    health_grade: "Needs work",
    health_score_explanation: {
      version: "health_score_explanation_v1",
      starting_score: 100,
      final_score: 60,
      total_deduction: 40,
      deductions: [
        { category: "Search visibility", points: 15 },
        { category: "Search appearance", points: 9 },
        { category: "Page content", points: 8 },
        { category: "Website setup", points: 8 },
      ],
      coverage_ceiling: 100,
      applied_ceiling: 100,
      ceiling_reason: "",
      floor_applied: false,
      verification_findings_excluded: true,
    },
    customer_summary: "FixList recognized this as finance / insurance / lead generation and used the finance / insurance / lead generation playbook. The scanner reviewed 150 pages out of about 184 discovered URLs. Start with the highest-impact items on loan program pages, application pages, quote/contact forms.",
    next_best_step: "Fix broken location-page template content",
    no_high_confidence_findings: false,
    completed_at: SEALED_AT,
    authority_seal_version: "standard_review_snapshot_hmac_v6_report_evidence",
    authority_sealed_at: SEALED_AT,
    crawl_timing: {},
    sampling_evidence: {},
  };
}

function liveFixList(run) {
  return {
    id: "6aa87a0513530c445fe4e62f",
    scan_run_id: run.id,
    project_id: run.project_id,
    website_url: run.website_url,
    ai_review_backend: "python_review_api",
    python_review_fallback_used: false,
    is_authoritative: true,
    health_score: 60,
    health_grade: "Needs work",
    scan_status: "complete",
    score_is_provisional: false,
    no_high_confidence_findings: false,
    total_fixes: 19,
    critical_count: 1,
    high_count: 13,
    medium_count: 3,
    low_count: 2,
    completed_count: 0,
    top_action_fix_ids: IDS.slice(0, 3),
    repair_contract_version: REPAIR_CONTRACT,
    repair_snapshot_contract_version: REPAIR_CONTRACT,
    repair_snapshot_contract_complete: true,
    repair_priority_model_version: REPAIR_PRIORITY,
    canonical_action_fix_ids: IDS,
    generated_at: SEALED_AT,
  };
}

function liveFixItem(fixList, index) {
  const priority = PRIORITIES[index];
  const action = ACTIONS[index];
  const rank = index + 1;
  const last = rank === 19;
  return {
    id: `live_row_${rank}`,
    fix_list_id: fixList.id,
    scan_run_id: fixList.scan_run_id,
    project_id: fixList.project_id,
    fix_id: IDS[index],
    rule: rank === 1 ? "broken_location_template_content" : last ? "potential_orphan_pages" : `live_rule_${rank}`,
    category: rank === 1 ? "web_dev" : last ? "indexability" : "technical",
    customer_category: rank === 1 ? "Website setup" : last ? "Indexability" : "Website setup",
    issue_title: rank === 1 ? "Fix broken location-page template content" : last ? "Verify sitemap-only pages are internally linked" : `Live finding ${rank}`,
    plain_english_explanation: "Bounded live-shape regression fixture.",
    why_it_matters: "Regression fixture only.",
    current_value: rank === 1 ? "#location#" : "",
    recommended_value: "Review the finding.",
    simple_next_step: "",
    page_scope: last ? "mixed" : rank === 1 ? "family" : "page",
    page_template_family: last ? "mixed" : rank === 1 ? "location_landing" : "",
    page_url: last ? "/loan-overview" : rank === 1 ? "/locations/alabama" : `/fixture-${rank}`,
    affected_pages: [last ? "/loan-overview" : rank === 1 ? "/locations/alabama" : `/fixture-${rank}`],
    source_pages: [last ? "/loan-overview" : rank === 1 ? "/locations/alabama" : `/fixture-${rank}`],
    evidence_status: last ? "needs_verification" : "",
    verification_state: last ? "needs_verification" : "",
    limitation_code: null,
    confidence_score: last ? 64 : 90,
    priority,
    difficulty: "easy",
    who_can_do_this: "you",
    requires_developer: rank === 1,
    requires_approval: rank !== 1,
    can_auto_fix: false,
    estimated_time: "about 5–15 minutes",
    user_status: "open",
    completed_at: null,
    completed_by_user_id: null,
    first_seen_scan_run_id: null,
    carried_over: false,
    page_count: 0,
    family_breakdown: {},
    representative_pages_by_family: {},
    what_to_do_steps: ["Review the finding."],
    metadata_state_counts: { missing: 0, malformed: 0, empty: 0 },
    combined_rules: [],
    grouping_explanation: null,
    repair_contract_version: REPAIR_CONTRACT,
    repair_snapshot_contract_version: REPAIR_CONTRACT,
    repair_snapshot_contract_complete: true,
    repair_priority_model_version: REPAIR_PRIORITY,
    base_severity: priority === "critical" ? "high" : priority,
    technical_severity_source: rank === 1 ? "defect_class" : "rule_taxonomy",
    evidence_class: last ? "opportunity" : rank === 1 ? "confirmed_problem" : "improvement",
    action_priority: action,
    action_priority_score: 5000 - rank,
    priority_reason: rank === 1 ? "60 of 60 location pages checked are affected." : last ? "Affected evidence includes 5 customer-journey pages." : "Live rank/count shape regression fixture.",
    canonical_action_rank: rank,
    repair_identity_version: "repair_identity_v2_technical",
    repair_fingerprint: rank === 1 ? "8452f066cd3862809244629c" : last ? "89d008db70708423fb4b6dc2" : `fixture_${String(rank).padStart(2, "0")}`,
    repair_identity_state: "provisional",
    repair_identity_stable: false,
    repair_surface: "",
    remediation_family: "",
    shared_repair_confirmed: false,
    priority_context: {
      version: REPAIR_PRIORITY,
      legacy_priority: priority,
      base_severity: priority === "critical" ? "high" : priority,
      technical_severity_source: rank === 1 ? "defect_class" : "rule_taxonomy",
      evidence_class: last ? "opportunity" : rank === 1 ? "confirmed_problem" : "improvement",
      action_priority: action,
      action_priority_score: 5000 - rank,
      search_facing: rank !== 1,
      affected_checked: rank === 1 ? 60 : last ? 68 : 1,
      checked_eligible: rank === 1 ? 60 : null,
      checked_coverage: rank === 1 ? 1 : null,
      indexable_affected: rank === 1 ? 60 : 0,
      non_indexable_affected: 0,
      unknown_indexability_affected: 0,
      indexable_checked_eligible: rank === 1 ? 60 : null,
      searchable_coverage: rank === 1 ? 1 : null,
      important_affected: last ? 5 : rank === 1 ? 60 : 0,
      shared_repair_confirmed: false,
      coverage_scope: "checked_sample",
    },
    repair_verification_state: null,
    rule_definition_version: null,
    comparison_profile_version: null,
    raw_finding: {
      verified_urls: [],
      ...(rank === 1 || last ? {
        repair_evidence_groups: [{
          fix_id: IDS[index],
          family: rank === 1 ? "location_landing" : "mixed",
          locale: "",
          representative_url: rank === 1 ? "/locations/alabama" : "/loan-overview",
          affected_urls: [rank === 1 ? "/locations/alabama" : "/loan-overview"],
          count: 1,
          priority,
          action_priority: action,
          evidence_class: last ? "opportunity" : "confirmed_problem",
          evidence_status: last ? "needs_verification" : "",
          verification_state: last ? "needs_verification" : "",
          repair_verification_state: "",
        }],
      } : {}),
      ...(last ? { non_scoring: true, score_impact: 0 } : {}),
    },
  };
}

test("Sep 15 live Base44 row shape rebuilds identically in V4 writer and reader", () => {
  const run = liveRun();
  const fixList = liveFixList(run);
  const fixItems = IDS.map((_, index) => liveFixItem(fixList, index));

  const writer = buildPersistedAuthoritySnapshot({ run, fixList, fixItems, userId: USER_ID, sealedAt: SEALED_AT });
  const reader = authoritySnapshotFromRows({ run, fixList, fixItems, userId: USER_ID });

  assert.deepEqual(reader, writer);
});
