// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs from
// data/beta-crawler-revision.json and data/cross-runtime-release-components.json.
// Run that generator after changing either input; CI fails on drift.

export const RELEASE_CONTRACT_SCHEMA_VERSION = "beta_crawler_revision_v1";
export const RELEASE_FINGERPRINT = "2387b9470d23a050";
export const RELEASE_STATUS = "candidate";
export const RELEASE_COMPONENT_VERSIONS = Object.freeze({
  "acceptance_evidence_version": "standard150_acceptance_evidence_v2_aggregate_rss_fail_closed",
  "admission_reconciliation_version": "admission_reconciliation_v1_exact_generation_barrier",
  "archetype_classifier_version": "archetype_classifier_v11_booking_competitor_finance_playbooks",
  "artifact_filter_version": "artifact_filter_v4_wordpress_route_noise",
  "authority_seal_version": "scan_evidence_hmac_sha256_v1",
  "canonical_href_resolution_version": "canonical_href_resolution_v2_absolute_single_label_same_path",
  "canonical_target_evidence_version": "canonical_target_evidence_v2_origin_alias_equivalence",
  "count_copy_version": "count_copy_v2_agreeing_verbs",
  "coverage_authority_evidence_version": "coverage_authority_evidence_v2_authoritative",
  "coverage_authority_version": "coverage_authority_v1_shared_decision",
  "crawler_acceptance_version": "crawler_acceptance_v1",
  "customer_projection_version": "customer_projection_v4_acceptance_evidence_fail_closed",
  "customer_result_reader_version": "customer_result_reader_v2_historical_release_compatibility",
  "durable_completion_contract_version": "durable_standard150_completion_v1",
  "durable_control_contract_version": "durable_standard150_control_v1",
  "durable_worker_contract_version": "scan_job_worker_v1_cloud_tasks",
  "evidence_quality_gate_version": "evidence_quality_gate_v2_shared_coverage_decision",
  "failure_evidence_dedup_version": "failure_evidence_dedup_v2_group_covered_page_rows",
  "failure_state_presentation_version": "failure_state_presentation_v1_durable_reason",
  "final_url_dedup_version": "final_url_dedup_v1_normalized_identity",
  "frontier_policy_version": "url_frontier_policy_v1_conservative_trap_guard",
  "grouped_recommendation_evidence_version": "grouped_recommendation_evidence_v1_metadata_states",
  "image_alt_evidence_version": "material_image_alt_v1",
  "indexability_quality_version": "indexability_quality_v1",
  "limited_result_integrity_version": "standard_limited_result_integrity_v2_acceptance_evidence",
  "metadata_evidence_version": "metadata_evidence_v1_description_states",
  "navigation_indexability_version": "navigation_indexability_v1",
  "orphan_asset_evidence_version": "orphan_asset_evidence_v1",
  "page_evidence_gate_version": "page_evidence_gate_v1",
  "page_level_asset_evidence_version": "page_level_asset_evidence_v3_markdown",
  "page_template_classifier_version": "page_template_classifier_v4_bookable_inventory_routes",
  "priority_summary_version": "priority_summary_v1_action_band_consistent",
  "quality_gate_version": "review_quality_gate_v3_shared_coverage_decision",
  "redirect_evidence_version": "redirect_evidence_v3_origin_alias_identity",
  "render_evidence_quality_version": "render_evidence_quality_v1",
  "render_evidence_version": "render_evidence_v1",
  "render_followup_version": "render_followup_v1",
  "repair_coverage_version": "repair_coverage_v4_corroborated_family_gap_fill",
  "repair_presentation_contract_version": "repair_presentation_v3_fingerprint_keyed_actions",
  "repair_suggestion_library_version": "v1",
  "repair_surface_grouping_version": "repair_surface_grouping_v1_shared_artifact",
  "repair_write_contract_version": "repair_contract_v2_shadow_calibrated",
  "representative_page_version": "business_representative_page_v3_sitewide_archetype_ranking",
  "review_attestation_version": "standard_review_snapshot_hmac_v3_acceptance_evidence",
  "review_evidence_calibration_version": "review_evidence_calibration_v6_health_score_v2",
  "review_version": "python_review_v2_structural_marketplace",
  "route_boundary_classifier_version": "route_boundary_classifier_v2_wordpress_author_archives",
  "sampling_version": "balanced_sitemap_buckets_v2_locale_collapsed_identity_reserve",
  "scan_history_delete_version": "scan_history_delete_v2_drain_children",
  "scan_history_version": "scan_history_v2_account_wide_recent",
  "scanner_build_revision": "authenticated_health_probe_v1",
  "scanner_version": "python_scanner_v3_bounded_request",
  "sitemap_parser_version": "sitemap_parser_v1_xml_identity",
  "sitemap_time_reservation_version": "sitemap_time_reservation_v1_crawl_first",
  "title_evidence_version": "title_evidence_v1_contextual_duplicates",
  "trust_discovery_version": "trust_page_discovery_v1",
  "trust_finding_gate_version": "trust_page_finding_gate_v1",
  "zero_fix_confidence_version": "python_review_v3_zero_fix_confidence"
});

/** Exact-match gate. A missing or unexpected marker is never substituted. */
export function releaseMarkersMatch(candidate) {
  if (!candidate || typeof candidate !== "object") return false;
  return String(candidate.beta_revision_fingerprint || "") === RELEASE_FINGERPRINT;
}
