// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/deleteCustomerScanData.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "36c6313669802b2f25bde2a7a749226dfe8e34448ccc9f0516d978fa5fd041e2";
