// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/startStandardScanJobV7.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "ead95e6ee89ed8bb8b5feb4c8ca110c43308398019b27a565c3cdac034e9456d";
