// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/durableScanWorkerControl.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "c00fcb00bea9cbe90151f44514975dd871090bf6bfbf06fe49b4cf172789d2cf";
