// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/durableScanWorkerControl.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "d752b4f619a7f78885a09c92c0ed5ad732d223034d0f671799b928336f896e16";
