// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/startStandardScanJobV6.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "286f5fe08b0d1d346969d8034769533d13d768f396f797f20d3702565a34a20c";
