// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/persistDurableScanAuthority.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "026a51c948b5e7325f6c5a31ee2387837124c7428040009a0bf4c07afbc73364";
