// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/persistDurableScanAuthority.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "b6db52364f6990ffe4419b839d0dbf81f32f38684a653931eb589e8baa638e90";
