// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/persistDurableScanAuthority.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "a0709d15d26e0dd315cfd4b5e47597a2a907a8010712331fbac640692832fde5";
