// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/durableScanWorkerControl.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "b7c29cadb7da61ffc56ed89a0fb81a2c76ddd4e1220d1bf082e778ca0d40cd92";
