// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/persistDurableScanAuthority.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "596661511e500a017ec78b11808df81c918bb0500d6a44a6f35e7d9f3caaf112";
