// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/deleteCustomerScanDataV7.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "c761e5c600c212253195979c84e186f53d7ee671709ccec5741f1937a4141883";
