// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/persistDurableScanAuthorityV8.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "8748e54cb9b1738e89095177c1cbbda1b5f364798db70d4e620fd147c32cbcfb";
