// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/persistDurableScanAuthorityV8.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "d822fcdf51d40863085fc015d7a4887026af64b777236f0f88ae211323bfa547";
