// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/startStandardScanJobV4.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "13aa054183d62cdd463380d04616b9b6004c501532679cdbde81673d9b413742";
