// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/persistDurableScanAuthority.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "5f516c8850bed48391101968eec0487ef4d3410c366554ef16b149da591b06c6";
