// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/stripeWebhook.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "29bc31930d998c72abe32af63e97e61b35b4f432feefaef77a6563dc79b4cbd3";
