// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/stripeWebhook.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "a2bc0ac8beb26b8c341b21dd044bc4aff0d68f873a41a62bad6e697112bc063d";
