// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/createAccessCheckout.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "e9756326e0b8f35c1f56cf8e1a669c9fb7aa625da030d7c6515defb5b8f616d7";
