// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/deleteCustomerScanDataV6.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "5905d079daa322f0d2eba0e5b879e08e88f46126b35e1abeea6eaf36694f5359";
