// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/deleteCustomerScanDataV3.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "db3380404bcf3825c213b4b3721b8ddb713f06e97bdb53ade59365d37be7bce8";
