// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/startStandardScanJobV5.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "b1f3e10b9d99fd2717a6d804f20b5a73bf15fdbb0bf9aaed13268381bb496efe";
