// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/startStandardScanJobV3.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "60a5a07b6ffb7e05bca8845fa6ffdb692be3695c8486e3641e64f79095eedf9a";
