// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/startStandardScanJob.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "0b5465cb2230724e1d2320413e24830ddff6131aaed22f8ddb57275bcbda2b71";
