// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/deleteCustomerScanDataV5.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "389191f260385829eeaa0bb595aa8efbbf7fd85a158322b94099914464cfc4f3";
