// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/ownerScanDebugControl.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "4feb2a114fe27603cc0663a425720d29ab56264aaa60bea7207924e2b0f9e8b9";
