// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/ownerScanDebugControl.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "6cd2c6722d221ffe85e451b0e3b1110cd0c313fd416b965c2854bebd279f9656";
