#!/usr/bin/env node
/**
 * Generate every runtime release contract from the one canonical input.
 *
 * Base44 function packages cannot import `../`, so each package that needs the
 * release contract receives its own generated, package-local file. The frontend
 * gets one too. All of them are derived from `data/beta-crawler-revision.json`
 * (the recorded candidate) plus `data/cross-runtime-release-components.json`
 * (the cross-runtime markers Python cannot import), so a copied literal can
 * never drift away from release truth again.
 *
 *   node scripts/generate_release_contracts.mjs            write the contracts
 *   node scripts/generate_release_contracts.mjs --check     fail on any drift
 *   node scripts/generate_release_contracts.mjs --list      list emitted paths
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// RELEASE_CONTRACT_ROOT lets a test drive the generator against an isolated
// copy. Tests run in parallel, so a check that mutated the real tree would race
// with any other test importing a generated contract.
const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const ROOT = process.env.RELEASE_CONTRACT_ROOT
  ? path.resolve(process.env.RELEASE_CONTRACT_ROOT)
  : REPO_ROOT;
const REVISION_RECORD = "data/beta-crawler-revision.json";
const CROSS_RUNTIME_INPUT = "data/cross-runtime-release-components.json";
const CROSS_RUNTIME_SCHEMA = "cross_runtime_release_components_v1";

// Every consumer that needs release identity at runtime. Base44 packages are
// package-local by necessity; the frontend has a single shared module.
// Only packages that actually import the contract are listed: the release
// manifest rejects an unreferenced file as dead bytes shipped through the
// bundler, so an unused generated contract is an integrity failure.
const CONSUMERS = [
  "src/lib/generatedReleaseContract.js",
  "base44/functions/persistDurableScanAuthority/generatedReleaseContract.js",
  "base44/functions/persistLimitedScanResult/generatedReleaseContract.js",
  "base44/functions/startStandardScanJob/generatedReleaseContract.js",
  "base44/functions/durableScanWorkerControl/generatedReleaseContract.js",
  "base44/functions/ownerScanDebugControl/generatedReleaseContract.js",
  "base44/functions/getCustomerScanResult/generatedReleaseContract.js",
  // Not in RELEASE_FUNCTIONS and not reachable from the live app, but they must
  // not be able to ship a stale marker if they are ever republished.
  "base44/functions/aiReviewScan/generatedReleaseContract.js",
  "base44/functions/persistScanAuthority/generatedReleaseContract.js",
  "base44/functions/grokChat/generatedReleaseContract.js",
];

// These Base44 entry modules are the deployable module identities. Base44 has
// previously reused a compiled release when entry.ts stayed byte-identical while
// imported release-sensitive code changed. The canonical generator therefore
// rewrites a fingerprint marker in each release-sensitive entry whenever the
// frozen release fingerprint moves.
const ENTRY_IDENTITY_CONSUMERS = [
  "base44/functions/persistDurableScanAuthority/entry.ts",
  "base44/functions/persistLimitedScanResult/entry.ts",
  "base44/functions/startStandardScanJob/entry.ts",
  "base44/functions/durableScanWorkerControl/entry.ts",
  "base44/functions/getCustomerScanResult/entry.ts",
];

function readJson(relative) {
  return JSON.parse(fs.readFileSync(path.join(ROOT, relative), "utf8"));
}

function contractSource() {
  const record = readJson(REVISION_RECORD);
  const input = readJson(CROSS_RUNTIME_INPUT);

  if (input.schema_version !== CROSS_RUNTIME_SCHEMA) {
    throw new Error(`Cross-runtime components must use ${CROSS_RUNTIME_SCHEMA}.`);
  }
  if (!/^[0-9a-f]{16}$/.test(String(record.fingerprint || ""))) {
    throw new Error("The recorded revision has no valid fingerprint.");
  }
  for (const [key, value] of Object.entries(input.components)) {
    if (record.component_versions?.[key] !== value) {
      throw new Error(
        `Cross-runtime component ${key} is not in the recorded fingerprint. `
        + "Re-run scanner-api/scripts/freeze_beta_revision.py first.",
      );
    }
  }

  // Sorted so the output is byte-identical for identical inputs.
  const components = Object.fromEntries(
    Object.entries(record.component_versions).sort(([a], [b]) => (a < b ? -1 : 1)),
  );

  return [
    "// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs from",
    `// ${REVISION_RECORD} and ${CROSS_RUNTIME_INPUT}.`,
    "// Run that generator after changing either input; CI fails on drift.",
    "",
    `export const RELEASE_CONTRACT_SCHEMA_VERSION = ${JSON.stringify(record.schema_version)};`,
    `export const RELEASE_FINGERPRINT = ${JSON.stringify(record.fingerprint)};`,
    `export const RELEASE_STATUS = ${JSON.stringify(record.status)};`,
    `export const RELEASE_COMPONENT_VERSIONS = Object.freeze(${JSON.stringify(components, null, 2)});`,
    "",
    "/** Exact-match gate. A missing or unexpected marker is never substituted. */",
    "export function releaseMarkersMatch(candidate) {",
    "  if (!candidate || typeof candidate !== \"object\") return false;",
    "  return String(candidate.beta_revision_fingerprint || \"\") === RELEASE_FINGERPRINT;",
    "}",
    "",
  ].join("\n");
}


function entryIdentitySource(source, fingerprint, relative) {
  const marker = /const BASE44_HANDLER_RELEASE_FINGERPRINT = "[0-9a-f]{16}";/;
  if (!marker.test(source)) {
    throw new Error(`Release-sensitive Base44 entry has no fingerprint marker: ${relative}`);
  }
  return source.replace(
    marker,
    `const BASE44_HANDLER_RELEASE_FINGERPRINT = "${fingerprint}";`,
  );
}

function main() {
  const mode = process.argv[2] || "";
  if (mode === "--list") {
    process.stdout.write(`${CONSUMERS.join("\n")}\n`);
    return 0;
  }

  const source = contractSource();
  const fingerprint = String(readJson(REVISION_RECORD).fingerprint || "");
  const drifted = [];
  for (const relative of CONSUMERS) {
    const target = path.join(ROOT, relative);
    const current = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : null;
    if (current === source) continue;
    if (mode === "--check") {
      drifted.push(relative);
      continue;
    }
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, source);
  }

  for (const relative of ENTRY_IDENTITY_CONSUMERS) {
    const target = path.join(ROOT, relative);
    if (!fs.existsSync(target)) {
      // Existing generator unit tests use isolated contract-only roots. The
      // real repository must always contain every deployable entry identity,
      // while isolated roots may omit entries unless that test is explicitly
      // exercising entry identity generation.
      if (ROOT === REPO_ROOT) {
        throw new Error(`Release-sensitive Base44 entry is missing: ${relative}`);
      }
      continue;
    }
    const current = fs.readFileSync(target, "utf8");
    const expected = entryIdentitySource(current, fingerprint, relative);
    if (current === expected) continue;
    if (mode === "--check") {
      drifted.push(relative);
      continue;
    }
    fs.writeFileSync(target, expected);
  }

  if (mode === "--check" && drifted.length > 0) {
    process.stderr.write(
      `Generated release contracts are out of date:\n  ${drifted.join("\n  ")}\n`
      + "Run: node scripts/generate_release_contracts.mjs\n",
    );
    return 1;
  }
  return 0;
}

process.exit(main());
