// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/durableScanWorkerControl.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "3d431eb26e5e0b7644ee1c10bd1762e05bf90734e416df8e5c831c9e5318c95d";
