// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/durableScanWorkerControl.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "88921820f45b80b5ffa3faa272ff8d2a088e28fe3f12ea9f494d42a5d03a51c6";
