// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/deleteCustomerScanDataV4.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "8622aecd90771ad2f2c7d0ed37d9aa9007258efca3dcecc9fb04dff4bd0196db";
