// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/deleteCustomerScanDataV8.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "2c5c8d8c4e876f6999a771d01bf3f60b9abf9a588f69347c9f9b6fd963945d26";
