// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/startStandardScanJob.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "0e5a6f23e743919a7a44fd271c4877f234512398b7359374b3eba08f382b5685";
