// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/startStandardScanJobV2.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "d3aea6e5568c7a744cad7ff5c3747e15dd1ed2af891454e464b8bf98d4ccc1f8";
