// DO NOT EDIT. Generated by scripts/generate_release_contracts.mjs.
// SHA-256 package identity for base44/functions/startStandardScanJob.
// Every regular package file is covered except generatedBuildId.js itself.

export const FUNCTION_BUILD_ID = "00f57f5d9874e8d63d0c5dc5f2a275c730e45219413097791eedde2f270eb84a";
